/**
 * Shared upload constants and URL helpers.
 *
 * This module must stay free of server-only imports (mongoose, fs) so that
 * client components can use the same whitelists and URL logic the API enforces.
 * Server-side helpers live in `uploads.server.ts`.
 */

export const UPLOAD_FOLDERS = [
  "products",
  "gallery",
  "pages",
  "results",
  "misc",
] as const;
export type UploadFolder = (typeof UPLOAD_FOLDERS)[number];

export const MAX_UPLOAD_BYTES = 8 * 1024 * 1024; // 8 MB

/** Mime type -> file extension. The keys double as the accept whitelist. */
export const ALLOWED_IMAGE_TYPES = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
  "image/gif": "gif",
} as const;

export type AllowedMimeType = keyof typeof ALLOWED_IMAGE_TYPES;

export const ACCEPT_ATTRIBUTE = Object.keys(ALLOWED_IMAGE_TYPES).join(",");

/** Route prefix that serves uploads back out of MongoDB. */
export const UPLOAD_URL_PREFIX = "/api/uploads/";

/** Legacy disk-backed prefix. These files do not survive a redeploy. */
export const LEGACY_UPLOAD_URL_PREFIX = "/uploads/";

export const PLACEHOLDER_IMAGE_SRC = "/placeholder-image.svg";

export function isUploadFolder(value: unknown): value is UploadFolder {
  return (
    typeof value === "string" &&
    (UPLOAD_FOLDERS as readonly string[]).includes(value)
  );
}

export function isAllowedMimeType(value: unknown): value is AllowedMimeType {
  return (
    typeof value === "string" && value in ALLOWED_IMAGE_TYPES
  );
}

/** True for URLs this app owns and can therefore delete. */
export function isManagedUploadUrl(url: string | null | undefined): boolean {
  return typeof url === "string" && url.startsWith(UPLOAD_URL_PREFIX);
}

/** True for the pre-serverless `/uploads/...` disk paths. */
export function isLegacyUploadUrl(url: string | null | undefined): boolean {
  return (
    typeof url === "string" && url.startsWith(LEGACY_UPLOAD_URL_PREFIX)
  );
}

/**
 * A filename is only ever generated by this app, but it also arrives from the
 * URL on the way back out. Reject anything that could escape the folder.
 */
export function isSafeFilename(filename: string): boolean {
  if (!filename || filename.length > 128) return false;
  if (filename.includes("..")) return false;
  if (filename.includes("/") || filename.includes("\\")) return false;
  if (filename.includes("\0")) return false;
  return /^[A-Za-z0-9._-]+$/.test(filename);
}

/** Split a managed upload URL back into its folder and filename. */
export function parseUploadUrl(
  url: string
): { folder: UploadFolder; filename: string } | null {
  if (!isManagedUploadUrl(url)) return null;

  const parts = url.slice(UPLOAD_URL_PREFIX.length).split("/");
  if (parts.length !== 2) return null;

  const [folder, filename] = parts;
  if (!isUploadFolder(folder) || !isSafeFilename(filename)) return null;

  return { folder, filename };
}

export function buildUploadUrl(folder: UploadFolder, filename: string): string {
  return `${UPLOAD_URL_PREFIX}${folder}/${filename}`;
}

/**
 * Resolve a stored image URL for rendering.
 *
 * Legacy `/uploads/...` paths pointed at the local disk and no longer resolve
 * on a serverless host, so they degrade to the placeholder rather than a
 * broken image. `designFallback` lets marketing pages keep their seeded
 * stand-in photography while the client's real images are outstanding.
 */
export function resolveImageSrc(
  url: string | null | undefined,
  designFallback?: string
): string {
  if (!url || isLegacyUploadUrl(url)) {
    return designFallback ?? PLACEHOLDER_IMAGE_SRC;
  }
  return url;
}

export function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
}
